cloud-bulldozer/orion

Dockerfile, requirements.txt
- Moving to 3.11.8 Python Docker image
- Updating our Dockerfile with the new integration
- Pining our Hunter work to v0.5.0
- Closes #
=> Update Dockerfile w/ new Hunter integration

.github/workflows/build-push.yaml
Updating our gh action for our container image
- Closes #
=> Fixing build-push

.github/workflows/build-push.yaml
This will only try to push the code to quay if the code is being merged to main 
=> only push when push to main

utils/orion_funcs.py
Updating logger config so that it will make our debugging easy with verbose details.
Tested in local gives verbose details
```
2024-05-12 00:12:16,983 [Orion:orion_funcs.py:65] INFO: Collecting Max_Aggregated_RSS_Usage
```
=> Updating logger config for easy debugging

examples/readout-netperf-tcp.yaml
Adding new configs for some of the standard data plane metrics for readout testing.
This will help jedi when compiling the week's report
Tested on 4.15 and 4.16
=> example config file for netperf tcp results

examples/payload-scale-415.yaml, examples/payload-scale-416.yaml
To be able to start integration in prow, want to add a 4.15 example config to use with the open qe elastic search 
- Closes #
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/51950/rehearse-51950-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-write_jobs_to_gsheet-get-orion-results/1790058882077298688/artifacts/get-orion-results/openshift-qe-orion/build-log.txt
=> Payload examples

orion.py
Minimal change of port as configurable for daemon mode
- Closes #
=> port change for daemon mode

Dockerfile, configs/trt-payload-cluster-density.yml
Looking to start Orion as a service on Sailplane
- Closes #
=> Cleaning up for server onboarding

examples/trt-external-payload-cluster-density.yaml
Need to have a config for our pub ES instance.
- Closes #
=> Adding external trt payload config

examples/trt-external-payload-crd-scale.yaml, examples/trt-external-payload-node-density.yaml
Missing
- crd-scale
- node-density
- Closes #
=> Missing control-plane workloads

examples/trt-external-payload-cluster-density.yaml, examples/trt-external-payload-crd-scale.yaml, examples/trt-external-payload-node-density.yaml
Allow the user to override the version in examples
- Closes #
=> Template out version

requirements.txt, test.bats
=> fmatch bumped to v0.0.9

orion.py, pkg/algorithms/algorithm.py, pkg/runTest.py, test.bats
Changed tests bug and a trivial bug fix.
- Closes #
=> changed tests and trivial bug fix

examples/ols-load-generator.yaml, pkg/utils.py
Adding a draft for OLS ci tests.
Tested in local and it worked as expected. Waiting on this [pre-requisite PR](https://github.com/openshift/release/pull/60530/files#diff-20ecc70a73ced1dff906e04faf9e95cda31b97b4873de7f8349dc134953be440) to be in so that we can send this PR for a review.
=> Adding OLS configuration yaml

ack/4.18_cluster-density_ack.yaml, ack/4.18_node-density_ack.yaml, ack/4.19_cluster-density_ack.yaml, ack/4.19_node-density_ack.yaml
Updating ack file for 4.18 and 4.19 as per the slack [thread](https://redhat-internal.slack.com/archives/C020CKMP6CT/p1738114349692529).
=> Adding ack for ovnCPU_avg w.r.t 4.18 & 4.19

examples/ols-load-generator.yaml, test.bats
Bug fix and adding CI test for OLS configuration
No issues till now as we are still in the on-boarding step.
Functionality will be verified through this PR.
=> Bug fix in ols configuration

ack/4.18_cluster-density_ack.yaml, ack/4.19_cluster-density_ack.yaml, ack/4.19_node-density_ack.yaml
Ack all alerts firing as they appear to be non-issues or fixed already.
=> ACK all alerts w/c Feb 20 2025

examples/trt-external-payload-node-density-cni.yaml
Adding node-density-cni config
=> add config for payload node-density-cni job

README.md, pkg/algorithms/edivisive/edivisive.py, pkg/config.py, pkg/utils.py
The `threshold` feature allows for the user to define an absolute value that if the change percentage of the metric is smaller than it it will be skipped. This can be at metric level or at a global level. Metric level takes precedence. Zero is default value.
The `depends_on` feature allows the user to add dependency between two metrics, if the metric is showing a change point, it will be ignored if the dependent metric does not have a change point.
- Supersedes #72 
```
payload-cluster-density-v2
==========================
time                 uuid      buildUrl                         podReadyLatency_P99    apiserverCPU_avg    ovnCPU_avg    etcdCPU_avg    kubelet_avg
-------------------  --------  -----------------------------  ---------------------  ------------------ …
```
=> Threshold feature + depends_on feature to eDivise algorithm

examples/ols-load-generator.yaml
Needs these features required to detect legit change points for Openshift Lightspeed service.
- Closes# Redundant notifications in this [slack-channel](https://redhat.enterprise.slack.com/archives/C08DG2UL422)
Tested and verified locally for all the tests variants.
=> Updating ols config to use threshold, context and correlation params

pkg/config.py
Bug fix that removes unnecessary validation for ACK file.
- Closes # Current CI test failure in main branch.
Verified and tested in local
```
orion cmd --config examples/ols-load-generator.yaml --hunter-analyze --ack ack/4.15_ols-load-generator-10w_ack.yaml
```
works as expected.
=> [Fix]Removing correlation validation for ACK flow

pkg/algorithms/edivisive/edivisive.py
Debug prints need to be removed
- Closes #
=> Remove prints

examples/ols-load-generator.yaml
Adding more to list of failures to be detected on orion.
More context: https://redhat-internal.slack.com/archives/C068JAU4Y0P/p1742906110101449
Through the CI tests.
=> Adding more status codes for OLS

ack/4.19_udn-l3_ack.yaml
add an ack for https://issues.redhat.com/browse/OCPBUGS-54508
=> ack for ovn PR 2501 regression in ovnk CPU

examples/med-scale-udn-l3.yaml
=> Adding med-scale udn config

examples/netobserv-diff-meta-index.yaml, pkg/utils.py
This depends on - https://github.com/cloud-bulldozer/py-commons/pull/32
Adding an example file for people to reference.
- Closes #
=> Allow user to use kube-burner index for metadata

examples/med-scale-udn-l3.yaml, examples/small-scale-udn-l3.yaml, examples/trt-external-payload-cluster-density.yaml, examples/trt-external-payload-node-density-cni.yaml, examples/trt-external-payload-node-density.yaml
=> Isolate to pull and periodic jobs

ack/4.18_cluster-density_ack.yaml, ack/4.19_cluster-density_ack.yaml
Adds ACKs for current changepoints.
=> Acks 2025 04 11

requirements.txt
Updating with newer fmatch v0.0.11
=> Update fmatch to v0.0.11

ack/4.18_cluster-density_ack.yaml, ack/4.19_cluster-density_ack.yaml, ack/4.20_cluster-density_ack.yaml, examples/trt-external-payload-cluster-density.yaml, examples/trt-external-payload-crd-scale.yaml, examples/trt-external-payload-node-density-cni.yaml, examples/trt-external-payload-node-density.yaml
Changepoints have alerted us to a change, but they are not concerning.
We can safely ACK.
=> PERFSCALE-3872 - ack investigated changepoints

examples/small-scale-udn-l3.yaml
Our results were showing both L2 and L3 results.
=> Needed to isolate l3 jobs

pkg/runTest.py
To improve error debugging
- Closes #
=> Log algorithm selection

examples/small-scale-udn-l2.yaml
Add a Orion config file for udn-l2
https://issues.redhat.com/browse/PERFSCALE-3787
Testing with Jenkins job https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/orion/97, but it failed because of an issue introduced by a previous pr. Discussing in slack thread https://redhat-internal.slack.com/archives/C05CDC19ZKJ/p1748336541088419
=> add small-scale-udn-l2.yaml

orion.py
set the loglevel but need to pass the level to the logger after setting it :(
=> Fix issue with stdout

examples/quay-load-test-stable-stage.yaml, examples/quay-load-test-stable.yaml
Adding orion config for the quay stage environment
CI tests through this PR.
=> Adding quay stage config

examples/metal-perfscale-cpt-node-density-heavy.yaml, examples/metal-perfscale-cpt-node-density.yaml, examples/metal-perfscale-cpt-virt-density.yaml
Add node-density support for BM
=> [PERFSCALE-3433] Add node-density support for BM

.github/workflows/pylint.yaml, requirements.txt
=> locked pylint version

examples/metal-perfscale-cpt-data-path.yaml, examples/metal-perfscale-cpt-node-density-heavy.yaml, examples/metal-perfscale-cpt-node-density.yaml, examples/metal-perfscale-cpt-virt-density.yaml, examples/metal-perfscale-cpt-virt-udn-density.yaml
=> PERFSCALE-3433 - Add threshold to all metal jobs

pkg/algorithms/algorithm.py, pkg/runTest.py, pkg/utils.py, requirements.txt
Adding version field. 
This depends on a new release of fmatch, so once this merges https://github.com/cloud-bulldozer/py-commons/pull/44/files and we cut a new release, I will update this PR to the latest fmatch.
=> Add version to output

examples/trt-external-payload-node-density-cni.yaml
=> Missing config values

examples/med-scale-udn-l2.yaml, examples/med-scale-udn-l3.yaml, examples/small-scale-udn-l2.yaml, examples/small-scale-udn-l3.yaml
Needed tolerance and direction for some values. Need to overhaul much of our configs.
=> Cleaning up UDN examples

.github/workflows/pylint.yaml, main.py, orion/daemon.py, orion/run_test.py, orion/utils.py
=> Sippy pr search

examples/olmv1.yaml
Added case ID for OLM test metrics so that they can be identified in Reportal easily.
- Closes #
=> add case id for OLM test metrics

.github/workflows/builders.yaml, .github/workflows/image-push.yaml, .github/workflows/pylint.yaml, .github/workflows/tests.yaml, .github/workflows/unit_tests.yaml, orion/config.py
By default the checkout action fetches the GH merge commit, leading to undesired outcomes, like testing code different of the PR's most recent commit
- Closes #
=> Checkout HEAD rather than merge commit

orion/run_test.py, test.bats
We need to get our metadata fixed. This is a temp solution until we get our metadata updated
=> Fix to isolate periodic jobs

orion/run_test.py
=> Reduce search string for payload jobs

main.py
Reduce noise with json
- Closes #
=> Stop normal output w/ JSON

examples/pod_disruption_scenarios.yaml, test.bats
Want to add in a way to specify the pod namespace to differentiate orion runs for the different scenarios we run 
- Closes #
=> Adding pod namespace variable

examples/med-scale-udn-l2.yaml, examples/med-scale-udn-l3.yaml, examples/small-scale-cluster-density.yaml, examples/small-scale-node-density-cni.yaml, examples/small-scale-udn-l2.yaml, examples/small-scale-udn-l3.yaml, examples/trt-external-payload-cluster-density.yaml, examples/trt-external-payload-node-density-cni.yaml, examples/trt-payload-cluster-density.yaml
Make this as one of the metrics we track regularly
=> add instantenous ovsVswitchd CPU and Mem to track

examples/trt-external-payload-cpu.yaml
Trying to collect all the namespaces and ensure we don't have regressions against any of them. This is only looking at the CPU metric, we should also consider creating one for memory
=> Config that attempts to look at all namespaces
