.github/workflows/pylint.yml
.gitignore
README.md
orion.py
requirements.txt
setup.py

Orion is cli tool which automates the process of writing scripts when you need csv files to find regressions in metrics. 
To run orion on your local, please follow the following instructions.
Building Orion is a straightforward process. Follow these commands:
Clone the current repository using git clone.
```
>> git clone <repository_url>
>> pip install venv
>> source venv/bin/activate
>> pip install -r requirements.txt
>> export ES_SERVER = <es_server_url>
>> pip install .
```
Executing Orion is as simple as building it. After following the build steps, run the following:
```
>> orion
```
- Related Issue #1 
- Closes #
- How were the fix/results from this change verified? …

Meet Orion

---

.github/workflows/build-push.yaml
Dockerfile

This Dockerfile will build in Hunter and Orion into a single container image.
- Related Issue #3 
- Closes #3

Adding Dockerfile

---

orion.py
requirements.txt

Saw that there was an update version of fmatch that I think we should go ahead and update
The set columns that were defined in get_metadata did not allow for defining extra variables like clusterType for rosa/hcp or defining infraNodeCounts 
- Closes #
```
tests :
- name : rosa-small-scale-cluster-density-v2
platform: AWS
workerNodesType: m5.xlarge
workerNodesCount: 24
benchmark: cluster-density-v2
ocpVersion: 4.15
networkType: OVNKubernetes
clusterType: rosa
masterNodesCount: 3
metrics : 
- metric : podReadyLatency
metricType : latency
- metric : …
```

Update fmatch version and not set keys

---

README.md
orion.py
requirements.txt

Using the changes in [fmatch pr](https://github.com/cloud-bulldozer/py-commons/pull/16) I was able to add in more options into the yaml and have a working ingress perf comparison 
- Closes #
2 sample configs: 
```
tests :
- name : rosa-small-scale-ingress
platform: AWS
workerNodesType: m5.xlarge
workerNodesCount: 9
benchmark: ingress-perf
ocpVersion: 4.15
networkType: OVNKubernetes
clusterType: rosa
masterNodesCount: 3
metrics : 
- metric: Termination
config.termination: passthrough
sample: "*"
config.serverReplicas: "*"
metric_of_interest: total_avg_rps …
```

Generic comparison

---

.gitignore
README.md
examples/small-scale-cluster-density.yaml
examples/small-scale-node-density-cni.yaml
orion.py
requirements.txt
utils/orion_funcs.py

Creating metadata as a new field would allow us to keep the metric and test name seperate and not have checks in the code.. This will help in generalization of fmatch/orion if we want it in the future.
- Related Issue #16 
- Closes #

Metadata change

---

orion.py

Cleaning up the orion help output
- Related Issue #24
- Closes #24

Cleaning up help

---

.github/workflows/pylint.yml
README.md
examples/small-scale-node-density-cni.yaml
orion.py
utils/orion_funcs.py

A lot of the times we have a set uuid (current run) or one in mind that it would be nice to not have to go get the metadata of the run, create a config file and then run. This would allow a user to set a uuid on command line and have the config file only define the metrics wanted to be collected 
- Closes #
Example: 
`orion --uuid dc9431e4-43c9-482d-861b-87ab11afbd3a --baseline 2076cfe3-00fc-4fdd-bf76-016bb31264f1`

Adding baseline and uuid options

---

orion.py

Trivial bug fix in baseline UUIDs split.
Verified in local in a hacky way.
```
>>> import re
>>> baseline="uuid1,uuid2, uuid3,uuid4 uuid5 uuid6, uuid7,uuid8,                uuid9"
>>> uuids = re.split(' |,',baseline)
>>> print(uuids)
['uuid1', 'uuid2', '', 'uuid3', 'uuid4', 'uuid5', 'uuid6', '', 'uuid7', 'uuid8', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'uuid9']
>>> uuids = [uuid for uuid in re.split(' |,',baseline) if uuid]
>>> print(uuids)
['uuid1', 'uuid2', 'uuid3', 'uuid4', 'uuid5', 'uuid6', 'uuid7', 'uuid8', 'uuid9']
>>> exit()
```

[Trivial] Refine uuid split

---

examples/small-scale-cluster-density.yaml
examples/small-scale-node-density-cni.yaml
orion.py
requirements.txt
utils/orion_funcs.py

Since it will be easier to check buildUrl from the console, this would be an addition to orion. I'm unable to add the hyperlinked text in this preview, but the terminal does show hyperlinked text. The reason moving to hyperlinked text is to keep the terminal readable and clean. If having the URL makes more sense, it can be updated
```
(venv) sboyapal orion (display-builds) >> orion --hunter-analyze
2024-02-12 22:46:11,108 - Orion - INFO - The test aws-small-scale-cluster-density-v2 has started
2024-02-12 22:46:11,109 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-02-12 22:46:11,656 - Matcher - INFO - Executing query against index=ripsaw-kube-burner*
2024-02-12 22:46:13,538 - Orion - INFO - Collecting podReadyLatency
2024-02-12 22:46:13,538 - Matcher - INFO - Executing …
```

display build URL for changepoint

---

orion.py
utils/orion_funcs.py

With the changes from https://github.com/cloud-bulldozer/orion/pull/15, when using the uuid and baseline parameters I had added, it was now throwing an error trying to find the buildUrl for each uuid. This will get that data without erroring 
- Closes #
`$orion --uuid $UUID --baseline $BASELINE_UUID --config examples/small-scale-node-density-cni.yaml --debug`
```
,uuid,timestamp,P99,apiserverCPU_cpu_avg,ovnCPU_cpu_avg,etcdCPU_cpu_avg,etcdDisk_duration_avg,buildUrl
0,26feeb47-3f7d-45b4-9926-f8f774a08385,2023-12-14T23:13:52.563810987Z,2000,22.75417174782207 …
```

Getting build urls for when uuid and baseline are set

---

orion.py
utils/orion_funcs.py

Some of the changes are from metadata change PR please ignore them. We output the change point detection in a tabular form which was inherently provided by hunter. Now we provide it as a json output in stdout with the use of the flag `--output` or `-o`, this flag defaults to `text` and can be set to `json`. Below is a concise version of the json output. This does not change the csv file output. This PR aims to just provide the logic for json output, this will be separated in daemon mode.
```
[{
"uuid": "5b06c830-be55-4c84-b4da-92720b55c304",
"timestamp": 1701866097,
"metrics": {
"etcdDisk_duration_avg": {
"value": 0.0134358362,
"percentage_change": 0
},
"P99": {
"value": 13000,
"percentage_change": 0
},
"etcdCPU_cpu_avg": {
"value": 8.6963812859,
"percentage_change": 0
}, …
```

Json output

---

examples/readout-control-plane-cdv2.yaml
examples/readout-control-plane-node-density.yaml

Adding new configs for some of the standard control plane metrics for readout testing.
* Reference: [4.15 Readout](https://docs.google.com/presentation/d/1-OysXItG245lMpWuFE9z71JbXi-xBV1yZpdktIu_ZCM/edit#slide=id.g266acf45bb9_0_54)
* Followed this doc to generate configs: [change point detection using orion](https://docs.google.com/document/d/1_x9spXfcLvAC6upx8kB4EwWMzBVdAaqs4d5wUsXk1Dg/edit) 
Tested them locally and could see results for 4.16

Adding sample readout configs for control plane tests

---

README.md
orion.py
pkg/algorithm.py
pkg/algorithmFactory.py
pkg/constants.py
pkg/daemon.py
pkg/edivisive.py
pkg/isolationForest.py
pkg/runTest.py
pkg/types.py
pkg/utils.py
requirements.txt

Support for anomaly detection added to orion, this allows the ability to add other algorithms as well. Below are the outputs of the anomaly detection run on small scale cdv2. It is to be noted that the deviation in percentage change reported is the change in percentage from the weighted mean over a window at that particular datapoint
```
(venv) sboyapal orion (anomaly-detection) >> orion cmd --anomaly-detection
2024-06-13 16:09:01,205 - Orion - INFO - file: orion.py - line: 76 - 🏹 Starting Orion in command-line mode
2024-06-13 16:09:01,207 - Orion - INFO - file: utils.py - line: 279 - The test aws-small-scale-cluster-density-v2 has started
2024-06-13 16:09:01,208 - Matcher - INFO - Executing query against index=ospst-perf-scale-ci-*
2024-06-13 16:09:02,108 - Matcher - INFO - Executing …
```

Anomaly detection using Isolation Forest

---

examples/readout-control-plane-cdv2.yaml
orion.py
pkg/edivisive.py
pkg/isolationForest.py
pkg/utils.py

The trt team requested to have the metric test in a single testcase and I renamed the metrics in the readout config. Please ignore linting. 
```
>> orion cmd --config /Users/sboyapal/Documents/Redhat/Shashank/orion/examples/trt-payload-cluster-density.yaml --hunter-analyze --convert-tinyurl --output-format='junit' --save-output-path='junit.xml'
<?xml version="1.0" ?>
<testsuites>
<testsuite name="payload-cluster-density-v2 nightly compare" failures="1" tests="5">
<testcase name="[Jira: PerfScale] podReadyLatency_P99 regression detection" timestamp="1721232203"/>
<testcase name="[Jira: kube-apiserver] apiserverCPU_avg regression detection" timestamp="1721232203"/>
<testcase name="[Jira: Networking / ovn-kubernetes] ovnCPU_avg regression detection" timestamp="1721232203"/>
<testcase …
```

add collapse in junit as a table, rename metrics in readout

---

orion.py
pkg/config.py
pkg/daemon.py
pkg/utils.py

Added templating to cmd mode.. to be merged after refactor PR #55 
- Related Issue #52 #38
- Closes #

Cmd templating

---

README.md
orion.py
pkg/utils.py
test.bats

This change will allow us to match uuids no matter there jobIterations. This is important for node-density because the number of iterations is calculated based on how many nodes are currently on the cluster and this number can fluctuate. 
- Closes #
The old way of running produces less results than the new flag
orion cmd --config examples/trt-external-payload-node-density.yaml --lookback 5d  --hunter-analyze 
```
,uuid,timestamp,podReadyLatency_P99,apiserverCPU_avg,ovnCPU_avg,etcdCPU_avg,kubelet_avg,buildUrl
0,0d472812-58c4-4d17-9241-595e54e789a1,2024-08-04T05:20:49.559886961Z,3000,8.346889860243925,2.4993164237465395,8.512982301910718,24.588333408037823,https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.17-ni …
```

Node densityn ignore iterations

---

orion.py
pkg/algorithms/algorithm.py
pkg/algorithms/edivisive/edivisive.py
pkg/algorithms/isolationforest/isolationForest.py
pkg/daemon.py
pkg/runTest.py
pkg/utils.py

The cmd will exit with status 1 on detection of regression. Merge after #56
```
(venv) sboyapal orion (exit-1) >> echo $?
1
```
- Related Issue #53
- Closes #

Exit 1 on regression detection

---

README.md
orion.py
pkg/algorithms/algorithm.py
pkg/algorithms/edivisive/edivisive.py
pkg/algorithms/isolationforest/isolationForest.py
pkg/daemon.py
pkg/runTest.py
pkg/utils.py

Added to lookback for n number of runs. Do not merge unit fmatch 0.0.9 and #57 is merged
```
(venv) sboyapal orion (max-lookback) >> orion cmd --hunter-analyze --lookback-size=15
2024-08-19 16:32:00,136 - Orion      - INFO - file: orion.py - line: 116 - 🏹 Starting Orion in command-line mode
2024-08-19 16:32:00,139 - Orion      - INFO - file: utils.py - line: 218 - The test aws-small-scale-cluster-density-v2 has started
2024-08-19 16:32:00,139 - Matcher    - INFO - file: matcher.py - line: 66 - Executing query against index=ospst-perf-scale-ci-*
2024-08-19 16:32:00,861 - Matcher    - INFO - file: matcher.py - line: 66 - Executing query against index=ospst-ripsaw-kube-burner*
2024-08-19 16:32:01,071 - Orion      - INFO - file: utils.py - line: 52 - Collecting podReadyLatency
2024-08-19 …
```

Max lookback

---

.github/workflows/builders.yaml
.github/workflows/ci-tests.yaml
.github/workflows/pylint.yaml

Adding CI tests on a pull request. More context [here](https://github.com/kube-burner/kube-burner-ocp/pull/116#discussion_r1790904368)
Verified the [workflow](https://github.com/vishnuchalla/orion/actions/runs/11224614356/job/31201714647) from the fork branch.

CI tests on pull request

---

.github/workflows/builders.yaml
.github/workflows/pylint.yaml
.github/workflows/tests.yaml
orion.py
pkg/config.py
requirements.txt

Fixes linting errors in the CI.
Tested in local by running same commands as in GH actions.
```
(my_env) vchalla@vchalla-thinkpadp1gen2:~/myforks/orion$ pylint -d C0103 -d R0912 -d R0917 $(git ls-files '*/*.py' '*.py')
-------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 9.95/10, +0.05)
```

Fix liniting errors and update lint workflow

---

examples/trt-external-payload-cluster-density.yaml
examples/trt-payload-cluster-density.yaml

Adding multus/monitoring
- Closes #

Adding additional metrics to track

---

ack/4.18_cluster-density_ack.yaml
ack/4.18_node-density_ack.yaml
ack/4.19_cluster-density_ack.yaml
ack/4.19_node-density_ack.yaml

ACK'ing the node-density UUID from the nightly we already have OCPBUGS-49613 open for.
- Related Issue: OCPBUGS-49613

ACK 4.18 node-density run linked to same cdv2 regression nightly

---

examples/ols-load-generator.yaml
pkg/algorithms/algorithm.py
pkg/utils.py
test.bats

Enabling collapse for both JSON and JUNIT output workflows. This will help us only look at changepoints and few points around it when `--collapse` is specified as a parameter.
It is very hard to interpret the entire output in JSON and JUNIT formats when this filter is not applied. Hoping for this code change to fix it.
JUNIT
```
orion cmd --config examples/readout-control-plane-cdv2.yaml --hunter-analyze --output-format junit --collapse
cdv2-kube-apiserver-etcd-249nodes
=================================
<?xml version="1.0" ?>
<testsuites>
<testsuite name="cdv2-kube-apiserver-etcd-249nodes nightly compare" failures="2" tests="4">
<testcase name=" CPU_Usage_kube-apiserver_avg regression detection" timestamp="1739904386">
<failure>
+----+--------------------------------------+---------------- …
```

Enabling collapse for both JSON and JUNIT output formats

---

examples/readout-ingress.yaml

Adding a metric file for the data points collected for ingress-perf
- Closes #
version=4.18 es_metadata_index=perf_scale_ci-* es_benchmark_index=ingress-perf* orion cmd --config examples/readout-ingress.yaml --lookback 15d --cmr

Adding ingress metric file

---

examples/metal-perfscale-cpt-virt-density.yaml
test.bats

Add support for the virt-density workload
```
orion cmd --config examples/metal-perfscale-cpt-virt-density.yaml --lookback 15d --hunter-analyze
2025-04-22 11:06:03,315 - Orion      - INFO - file: orion.py - line: 125 - 🏹 Starting Orion in command-line mode
2025-04-22 11:06:03,321 - Orion      - INFO - file: utils.py - line: 241 - The test metal-perfscale-cpt-virtdensity has started
2025-04-22 11:06:03,321 - Matcher    - INFO - file: matcher.py - line: 65 - Executing query against index=perf_scale_ci-*
2025-04-22 11:06:03,737 - Matcher    - INFO - file: matcher.py - line: 65 - Executing query against index=ripsaw-kube-burner-*
2025-04-22 11:06:03,864 - Orion      - INFO - file: utils.py - line: 52 - Collecting vmiReadyLatency
2025-04-22 11:06:03,864 - Matcher    - INFO - file: matcher.py - …
```

[PERFSCALE-3433] Add virt-density support

---

examples/med-scale-udn-l2.yaml
examples/med-scale-udn-l3.yaml
examples/small-scale-udn-l3.yaml

udn jobName in orion config is not same as https://github.com/kube-burner/kube-burner-ocp/blob/main/cmd/config/udn-density-pods/udn-density-pods.yml#L82
Discussing in slack thread https://redhat-internal.slack.com/archives/C05CDC19ZKJ/p1748336541088419
L3: https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/orion/102/console passed
```
05-28 11:23:33.483  time                       uuid                                  buildUrl                                                                                                                                                                                                                                timestamp    podReadyLatency_P99    ovsCPU_avg    ovnkCPU-overall_avg …
```

fix udn jobName and add med-scale-udn-l2 config

---

examples/chaos_results.yaml
pkg/runTest.py
pkg/utils.py
requirements.txt
test.bats

Adds support for custom UUID and version fields. Will be use for Chaos Onboarding.
https://issues.redhat.com/browse/CHAOS-1028 
- Related Issue #https://github.com/cloud-bulldozer/orion/issues/98
https://github.com/cloud-bulldozer/py-commons/pull/39
```
tests :
- name : chaos
index: krkn-telemetry*
benchmarkIndex: krkn-metrics*
version: cluster_version
uuid_field: run_uuid
metadata:
cloud_infrastructure.keyword: AWS
cluster_version: 4.19
scenarios.scenario_type: pod_disruption_scenarios
scenarios.affected_pods.recovered.namespace: openshift-monitoring
```

Adding custom uuid field

---

pkg/constants.py
pkg/utils.py

The current logic does not work well. There're cases where nanoseconds are rounded up and the number of characters is different than expected, that's causing an exception, as demonstrated below.
```shell
ES_BENCHMARK_INDEX=ripsaw-kube-burner-* ES_METADATA_INDEX=perf_scale_ci-* VERSION=4.19 orion cmd --node-count true --config examples/trt-external-payload-node-density.yaml --lookback 7d --hunter-analyze --output-format junit --save-output-path=junit.xml 
2025-07-16 10:15:38,951 - Orion      - INFO - file: orion.py - line: 127 - 🏹 Starting Orion in command-line mode
2025-07-16 10:15:38,956 - Orion      - INFO - file: utils.py - line: 300 - The test payload-node-density has started
2025-07-16 10:15:38,956 - Matcher    - INFO - file: matcher.py - line: 69 - Executing query against …
```

Fix timestamp standardization logic

---

examples/olmv1.yaml

As title, add `OLM` example. However, 
- Got the `No UUID present for given metadata` failure. Which `metadata` I should use for local testing? Thanks!
```console
export ES_SERVER=https://$ES_USERNAME:$ES_PASSWORD@search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com
export ES_PASSWORD=xxx
export ES_USERNAME=xxx
export es_metadata_index='perf_scale_ci-*'
export es_benchmark_index='ripsaw-kube-burner-*'
export version=4.19
(venv) jiazha-mac:orion jiazha$ orion cmd --config examples/olmv1.yaml --lookback 7d --hunter-analyze --output-format junit --save-output-path=junit.xml --debug
2025-07-17 18:36:32,861 - Orion      - INFO - file: orion.py - line: 127 - 🏹 Starting Orion in command-line mode
2025-07-17 18:36:32,862 - Orion      - DEBUG - file: config.py - …
```

add OLMv1 example for GCP

---

ack/4.19_udn-l3_ack.yaml

4.19 orion failure 
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2688/pull-ci-openshift-ovn-kubernetes-release-4.19-qe-perfscale-aws-ovn-small-udn-density-l3/1948389383610568704/artifacts/qe-perfscale-aws-ovn-small-udn-density-l3/openshift-qe-orion-udn-l3/build-log.txt 
4.20 failures are due to pull jobs which include churn, no action for now
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-eng-ocp-qe-
perfscale-ci-main-aws-4.20-nightly-x86-udn-density-l3-24nodes/1948564249907302400/artifacts/udn-density-l3-24nodes/openshift-qe-orion-udn-l3/build-log.txt

ack 419 udn change caused by kube-burner metrics collection

---

orion/algorithms/algorithm.py
orion/algorithms/algorithmFactory.py
orion/matcher.py
orion/run_test.py
orion/utils.py
test.bats

In generate_tabular_output it was expecting a uuid but none was passed from the caller function. Adding uuid field to it and adding other output options for chaos scenario tests for catching this in the future 
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/68318/rehearse-68318-periodic-ci-redhat-chaos-prow-scripts-main-cr-4.19-nightly-krkn-hub-node-orion/1960056053794082816/artifacts/krkn-hub-node-orion/redhat-chaos-orion-node-tests-control-plane/build-log.txt
- Closes #

Adding uuid field for tabular output

---

orion/matcher.py

Our telemetry data was using underscores instead of camel case so to keep with the same keys I added build_url to our data. Want orion to still be able to give the build url using a slightly different key. 
- Closes #
Properly prints build urls
```
time                       uuid                                  ocpVersion    buildUrl …
```

Adding build url with underscore

---

examples/okd-control-plane-cluster-density.yaml
examples/okd-control-plane-crd-scale.yaml
examples/okd-control-plane-node-density-cni.yaml
examples/okd-control-plane-node-density.yaml

```
$ VERSION=4.19 orion --config examples/okd-control-plane-node-density-cni.yaml --lookback 60d  --hunter-analyze --es-server=xx --metadata-index=xx --benchmark-index=xx
2025-09-14 10:12:46,836 - Orion      - INFO - file: main.py - line: 134 - 🏹 Starting Orion in command-line mode
2025-09-14 10:12:46,848 - Orion      - INFO - file: utils.py - line: 288 - The test okd-node-density-cni-6nodes has started
2025-09-14 10:12:46,849 - Orion      - INFO - file: matcher.py - line: 73 - Executing query against index: perf_scale_ci-*
2025-09-14 10:12:48,084 - Orion      - INFO - file: matcher.py - line: 73 - Executing query against index: perf_scale_ci-*
2025-09-14 10:12:49,341 - Orion      - INFO - file: matcher.py - line: 73 - Executing query against index: ripsaw-kube-burner-*
2025-09-14 …
```

[PERFSCALE-4163] OKD control plane config files
